version: "3.8"

services:
  db:
    image: postgres:15
    container_name: user_service_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rideshare_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  user-service:
    build: ./services/user-services
    container_name: user_service_api
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/rideshare_db
      SECRET_KEY: BreakingTheMonolithWithIEEECSCUET
    ports:
      - "8000:8000"
    volumes:
      - ./services/user-services:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  nginx:
    image: nginx:latest
    container_name: api_gateway
    depends_on:
      - user-service
    ports:
      - "8080:80"  # Nginx Gateway exposed on localhost:8080
    volumes:
      - ./api_gateway/nginx.conf:/etc/nginx/conf.d/default.conf:ro  # Use our custom config
    restart: always

volumes:
  postgres_data:
