version: '3.8'

services:
  cuet-rickshaw-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    networks:
      - cuet-rickshaw-dev-network
    restart: unless-stopped

  postgres-dev:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: cuet_rickshaw_dev
      POSTGRES_USER: cuet_user
      POSTGRES_PASSWORD: cuet_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - cuet-rickshaw-dev-network

  redis-dev:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    networks:
      - cuet-rickshaw-dev-network

volumes:
  postgres_dev_data:

networks:
  cuet-rickshaw-dev-network:
    driver: bridge
