version: '3.8'

services:
  # CUET Rickshaw Frontend
  cuet-rickshaw-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8080
      - NEXT_PUBLIC_USER_SERVICE_URL=http://user-service:8080
      - NEXT_PUBLIC_RIDE_SERVICE_URL=http://ride-service:8081
      - NEXT_PUBLIC_LOCATION_SERVICE_URL=http://location-service:8082
      - NEXT_PUBLIC_PAYMENT_SERVICE_URL=http://payment-service:8083
      - NEXT_PUBLIC_NOTIFICATION_SERVICE_URL=http://notification-service:8084
    depends_on:
      - user-service
      - ride-service
      - location-service
      - payment-service
      - notification-service
      - postgres
      - redis
    networks:
      - cuet-rickshaw-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: cuet_rickshaw
      POSTGRES_USER: cuet_user
      POSTGRES_PASSWORD: cuet_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - cuet-rickshaw-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cuet_user -d cuet_rickshaw"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - cuet-rickshaw-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # User Service (Mock)
  user-service:
    image: mockserver/mockserver:latest
    ports:
      - "8080:1080"
    environment:
      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/user-service-expectations.json
    volumes:
      - ./mock-services/user-service-expectations.json:/config/user-service-expectations.json
      - ./mock-services/mockserver.properties:/config/mockserver.properties
    networks:
      - cuet-rickshaw-network
    restart: unless-stopped

  # Ride Service (Mock)
  ride-service:
    image: mockserver/mockserver:latest
    ports:
      - "8081:1080"
    environment:
      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/ride-service-expectations.json
    volumes:
      - ./mock-services/ride-service-expectations.json:/config/ride-service-expectations.json
      - ./mock-services/mockserver.properties:/config/mockserver.properties
    networks:
      - cuet-rickshaw-network
    restart: unless-stopped

  # Location Service (Mock)
  location-service:
    image: mockserver/mockserver:latest
    ports:
      - "8082:1080"
    environment:
      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/location-service-expectations.json
    volumes:
      - ./mock-services/location-service-expectations.json:/config/location-service-expectations.json
      - ./mock-services/mockserver.properties:/config/mockserver.properties
    networks:
      - cuet-rickshaw-network
    restart: unless-stopped

  # Payment Service (Mock)
  payment-service:
    image: mockserver/mockserver:latest
    ports:
      - "8083:1080"
    environment:
      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/payment-service-expectations.json
    volumes:
      - ./mock-services/payment-service-expectations.json:/config/payment-service-expectations.json
      - ./mock-services/mockserver.properties:/config/mockserver.properties
    networks:
      - cuet-rickshaw-network
    restart: unless-stopped

  # Notification Service (Mock)
  notification-service:
    image: mockserver/mockserver:latest
    ports:
      - "8084:1080"
    environment:
      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/notification-service-expectations.json
    volumes:
      - ./mock-services/notification-service-expectations.json:/config/notification-service-expectations.json
      - ./mock-services/mockserver.properties:/config/mockserver.properties
    networks:
      - cuet-rickshaw-network
    restart: unless-stopped

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - cuet-rickshaw-app
    networks:
      - cuet-rickshaw-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  cuet-rickshaw-network:
    driver: bridge
