version: '3.8'

services:
  notification_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rickshawx_notification_service
    ports:
      - "8084:8084"
    environment:
      - DATABASE_URL=postgresql://rickshawx_user:password123@host.docker.internal:5432/rickshawx_notification_db
      - REDIS_URL=redis://host.docker.internal:6379/4
      - RABBITMQ_URL=amqp://rickshawx_user:password123@host.docker.internal:5672/
      - USER_SERVICE_URL=http://host.docker.internal:8080
      - JWT_SECRET_KEY=your-super-secret-jwt-key-change-in-production
      - JWT_ALGORITHM=HS256
      - ENVIRONMENT=development
      - LOG_LEVEL=INFO
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=your_email@gmail.com
      - SMTP_PASSWORD=your_app_password
      - SMTP_USE_TLS=true
      - TWILIO_ACCOUNT_SID=your_twilio_account_sid
      - TWILIO_AUTH_TOKEN=your_twilio_auth_token
      - TWILIO_PHONE_NUMBER=+1234567890
      - FIREBASE_CREDENTIALS_PATH=/app/firebase-credentials.json
      - NOTIFICATION_RETRY_ATTEMPTS=3
      - NOTIFICATION_RETRY_DELAY_SECONDS=5
    volumes:
      - ./logs:/app/logs
      - ./firebase-credentials.json:/app/firebase-credentials.json:ro
    networks:
      - rickshawx_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  rickshawx_network:
    driver: bridge 