version: '3.8'

services:
  ride_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rickshawx_ride_service
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgresql://rickshawx_user:password123@host.docker.internal:5432/rickshawx_ride_db
      - REDIS_URL=redis://host.docker.internal:6379/1
      - RABBITMQ_URL=amqp://rickshawx_user:password123@host.docker.internal:5672/
      - USER_SERVICE_URL=http://host.docker.internal:8080
      - LOCATION_SERVICE_URL=http://host.docker.internal:8082
      - PAYMENT_SERVICE_URL=http://host.docker.internal:8083
      - NOTIFICATION_SERVICE_URL=http://host.docker.internal:8084
      - JWT_SECRET_KEY=your-super-secret-jwt-key-change-in-production
      - JWT_ALGORITHM=HS256
      - ENVIRONMENT=development
      - LOG_LEVEL=INFO
      - RIDE_MATCHING_RADIUS_KM=5.0
      - RIDE_TIMEOUT_MINUTES=15
    volumes:
      - ./logs:/app/logs
    networks:
      - rickshawx_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  rickshawx_network:
    driver: bridge 